from enum import Enum


class Role(str, Enum):
    ADMIN = "ADMIN"
    SALES_MANAGER = "SALES_MANAGER"
    SALES_REP = "SALES_REP"
    FINANCE = "FINANCE"
    CUSTOMER = "CUSTOMER"


class DealStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    UNDER_NEGOTIATION = "UNDER_NEGOTIATION"
    CONFIRMED = "CONFIRMED"
    IN_FULFILLMENT = "IN_FULFILLMENT"
    FULFILLED = "FULFILLED"
    INVOICED = "INVOICED"
    PAID = "PAID"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class ApprovalState(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    EVALUATED_NO_APPROVAL = "EVALUATED_NO_APPROVAL"
    PENDING_MANAGER = "PENDING_MANAGER"
    PENDING_FINANCE = "PENDING_FINANCE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED = "RETURNED"
    INVALIDATED = "INVALIDATED"


class ApprovalLevel(str, Enum):
    NONE = "NONE"
    MANAGER = "MANAGER"
    MANAGER_AND_FINANCE = "MANAGER_AND_FINANCE"


class ApprovalRequestStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED = "RETURNED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"


class ApprovalActionType(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    RETURN = "RETURN"
    ESCALATE = "ESCALATE"
    INVALIDATE = "INVALIDATE"


class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskFactorType(str, Enum):
    DISCOUNT_EXCESS = "DISCOUNT_EXCESS"
    MARGIN_EXPOSURE = "MARGIN_EXPOSURE"
    INVENTORY_RISK = "INVENTORY_RISK"
    APPROVAL_DELAY = "APPROVAL_DELAY"
    NEGOTIATION_PRESSURE = "NEGOTIATION_PRESSURE"


class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    WATCH = "WATCH"
    AT_RISK = "AT_RISK"


class TriggerType(str, Enum):
    DEAL_CREATED = "DEAL_CREATED"
    DISCOUNT_CHANGED = "DISCOUNT_CHANGED"
    LINE_ADDED = "LINE_ADDED"
    LINE_REMOVED = "LINE_REMOVED"
    QUANTITY_CHANGED = "QUANTITY_CHANGED"
    CUSTOMER_NEGOTIATED = "CUSTOMER_NEGOTIATED"
    NEGOTIATION_ACCEPTED = "NEGOTIATION_ACCEPTED"
    APPROVAL_COMPLETED = "APPROVAL_COMPLETED"
    STOCK_CHANGED = "STOCK_CHANGED"
    ORDER_STALLED = "ORDER_STALLED"
    MANUAL = "MANUAL"
    SYNC = "SYNC"


class MaterialChangeKind(str, Enum):
    DISCOUNT = "DISCOUNT"
    QUANTITY = "QUANTITY"
    LINE_ADDED = "LINE_ADDED"
    LINE_REMOVED = "LINE_REMOVED"
    CUSTOMER_COUNTER = "CUSTOMER_COUNTER"
    PAYMENT_TERMS = "PAYMENT_TERMS"
    SUBSCRIPTION_TERMS = "SUBSCRIPTION_TERMS"
    FULFILLMENT_RISK = "FULFILLMENT_RISK"


class NegotiationRequestType(str, Enum):
    COMMENT = "COMMENT"
    QTY_CHANGE = "QTY_CHANGE"
    REMOVE_LINE = "REMOVE_LINE"
    ADD_LINE = "ADD_LINE"
    COUNTER_DISCOUNT = "COUNTER_DISCOUNT"


class NegotiationRequestStatus(str, Enum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COUNTERED = "COUNTERED"
    WITHDRAWN = "WITHDRAWN"


class FulfillmentPlanStatus(str, Enum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    OVERRIDDEN = "OVERRIDDEN"
    APPLIED = "APPLIED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class RecommendationType(str, Enum):
    CROSS_SELL = "CROSS_SELL"
    UPSELL = "UPSELL"


class RecommendationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ADDED = "ADDED"
    DISMISSED = "DISMISSED"
    EXPIRED = "EXPIRED"


class AlertType(str, Enum):
    STALLED_DEAL = "STALLED_DEAL"
    DISCOUNT_ANOMALY = "DISCOUNT_ANOMALY"
    DELIVERY_SLIPPAGE = "DELIVERY_SLIPPAGE"
    APPROVAL_DELAY = "APPROVAL_DELAY"


class AlertStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class NextBestActionType(str, Enum):
    FINANCE_APPROVAL_REQUIRED = "FINANCE_APPROVAL_REQUIRED"
    MANAGER_APPROVAL_REQUIRED = "MANAGER_APPROVAL_REQUIRED"
    REDUCE_DISCOUNT = "REDUCE_DISCOUNT"
    RESTORE_MARGIN = "RESTORE_MARGIN"
    REAPPROVAL_REQUIRED = "REAPPROVAL_REQUIRED"
    RESPOND_TO_CUSTOMER = "RESPOND_TO_CUSTOMER"
    ACCEPT_FULFILLMENT_PLAN = "ACCEPT_FULFILLMENT_PLAN"
    CONSOLIDATE_BACKORDER = "CONSOLIDATE_BACKORDER"
    ADD_RECOMMENDATION = "ADD_RECOMMENDATION"
    SEND_TO_CUSTOMER = "SEND_TO_CUSTOMER"
    FOLLOW_UP_CUSTOMER = "FOLLOW_UP_CUSTOMER"
    CONFIRM_ORDER = "CONFIRM_ORDER"
    AWAITING_APPROVER = "AWAITING_APPROVER"
    NONE = "NONE"


class AuditEventType(str, Enum):
    DEAL_CREATED = "DEAL_CREATED"
    DEAL_SYNCED = "DEAL_SYNCED"
    DISCOUNT_CHANGED = "DISCOUNT_CHANGED"
    LINE_CHANGED = "LINE_CHANGED"
    RISK_RECALCULATED = "RISK_RECALCULATED"
    APPROVAL_CREATED = "APPROVAL_CREATED"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_RETURNED = "APPROVAL_RETURNED"
    APPROVAL_ESCALATED = "APPROVAL_ESCALATED"
    APPROVAL_INVALIDATED = "APPROVAL_INVALIDATED"
    NEGOTIATION_RECEIVED = "NEGOTIATION_RECEIVED"
    NEGOTIATION_RESPONDED = "NEGOTIATION_RESPONDED"
    NEGOTIATION_WITHDRAWN = "NEGOTIATION_WITHDRAWN"
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"
    FULFILLMENT_PLANNED = "FULFILLMENT_PLANNED"
    FULFILLMENT_ACCEPTED = "FULFILLMENT_ACCEPTED"
    FULFILLMENT_OVERRIDDEN = "FULFILLMENT_OVERRIDDEN"
    FULFILLMENT_APPLIED = "FULFILLMENT_APPLIED"
    FULFILLMENT_REPLANNED = "FULFILLMENT_REPLANNED"
    RECOMMENDATION_ADDED = "RECOMMENDATION_ADDED"
    RECOMMENDATION_DISMISSED = "RECOMMENDATION_DISMISSED"
    ORDER_SENT = "ORDER_SENT"
    QUOTATION_SENT = "ORDER_SENT"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    INVOICE_CREATED = "INVOICE_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    HEALTH_RECALCULATED = "HEALTH_RECALCULATED"
    ALERT_RAISED = "ALERT_RAISED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    NUDGE_SENT = "NUDGE_SENT"
    ESCALATION_SENT = "ESCALATION_SENT"
    LOGIN = "LOGIN"
    MAGIC_LINK_ISSUED = "MAGIC_LINK_ISSUED"
    MAGIC_LINK_USED = "MAGIC_LINK_USED"
